services:
  traefik:
    image: traefik:v3.0
    container_name: orgnote-traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./deploy/traefik/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - traefik-letsencrypt:/letsencrypt
    environment:
      - ACME_EMAIL=${ACME_EMAIL}
    networks:
      - traefik-network

volumes:
  traefik-letsencrypt:

networks:
  traefik-network:
    name: traefik-network
    driver: bridge
